/*
 * This file is part of the PocketSVG package.
 * Copyright (c) Ponderwell, Ariel Elkin, Fjölnir Ásgeirsson, and Contributors
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

#import <QuartzCore/QuartzCore.h>

NS_ASSUME_NONNULL_BEGIN

@class SVGBezierPath;

/// A CALayer subclass that renders an SVG file.
@interface SVGLayer : CALayer

/*!
 *  @discussion Initialises a layer that renders the SVG file at the URL.
 *
 *  @param url The URL of the SVG file.
 */
- (instancetype)initWithContentsOfURL:(NSURL *)url;

/*!
 *  @discussion The SVG paths the layer should draw.
 *
 *  @param paths the paths to draw
 */
@property (nonatomic, copy) NSArray<SVGBezierPath*> *paths;

/*!
 *  @discussion Solidly fills the shape formed by the SVG path with the given color.
 *
 *  @param fillColor A color to fill the SVG shape with.
 */
@property(nonatomic) CGColorRef fillColor;


/*!
 *  @discussion Solidly colors the path generated by the SVG file.
 *
 *  @param strokeColor The color to stroke the path with.
 */
@property(nonatomic) CGColorRef strokeColor;


/*!
 *  @discussion Specifies whether or not line thickness should be scaled
 when scaling paths.
 */
@property(nonatomic) BOOL scaleLineWidth;

@end
NS_ASSUME_NONNULL_END
